### ISSUE TITLE
New setuptools release prevents install of python core library

### ISSUE THREAD

**Issue by melvin806** [IBM/python-sdk-core#202] opened 2024-07-29 03:57 UTC
Hi

I followed the instructions to upgrade the package
python -m pip install --upgrade ibm-cloud-sdk-core

i am running on wsl,
i am running on python 3.9 inside wsl
my setuptools-72.0.0

But i am getting this error, may i know what i am missing?
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      
        File "/tmp/pip-build-env-nz566fgr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-nz566fgr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nz566fgr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-nz566fgr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

**Comment by vinothsubramanian** [comment] 2024-07-29 04:35
I confirm that the same issue occurs using uv. 
```
uv pip install -r .\requirements.txt
⠴ ibm-cloud-sdk-core==3.20.3                                                                                                                                                            
error: Failed to download and build 'ibm-cloud-sdk-core==3.20.3'
  Caused by: Failed to build: 'ibm-cloud-sdk-core==3.20.3'
  Caused by: Build backend failed to determine extra requires with 'build_wheel()' with exit code: 1
stdout:

--- stderr:
<string>:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\myuserid\AppData\Local\uv\cache\builds-v0\.tmp8oeKOV\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuserid\AppData\Local\uv\cache\builds-v0\.tmp8oeKOV\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "C:\Users\myuserid\AppData\Local\uv\cache\builds-v0\.tmp8oeKOV\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\myuserid\AppData\Local\uv\cache\builds-v0\.tmp8oeKOV\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 20, in <module>
ModuleNotFoundError: No module named 'setuptools.command.test'
---
```

**Comment by vinothsubramanian** [comment] 2024-07-29 05:35
> solved by installing with --no-build-isolation

Seems to be the [workaround](https://github.com/pypa/setuptools/issues/4519#issuecomment-2254978228) for now

**Comment by willwade** [comment] 2024-07-29 05:40
+1 from me. this is stopping ci builds on 3.12

**Comment by suresh-at-straker** [comment] 2024-07-29 05:43
similar issue for me. 

Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
...
...
Getting requirements to build wheel did not run successfully.
 exit code: 1

**Comment by willwade** [comment] 2024-07-29 06:09
I'm intrigued. why has this started overnight? Whats changed? (the workarounds arent working for me sadly)

**Comment by vinothsubramanian** [comment] 2024-07-29 06:29
@willwade There is an [release to setuptools ](https://github.com/pypa/setuptools/releases/tag/v72.0.0) published today. That seems to be the root cause of the issue.

**Comment by melvin806** [comment] 2024-07-29 07:41
> > solved by installing with --no-build-isolation
> 
> Seems to be the [workaround](https://github.com/pypa/setuptools/issues/4519#issuecomment-2254978228) for now

but how did you apply the workaround onto the cicd pipeline? i cant build any new build images

**Comment by willwade** [comment] 2024-07-29 11:44
> > > solved by installing with --no-build-isolation
> > 
> > 
> > Seems to be the [workaround](https://github.com/pypa/setuptools/issues/4519#issuecomment-2254978228) for now
> 
> but how did you apply the workaround onto the cicd pipeline? i cant build any new build images

https://github.com/pypa/setuptools/issues/4519#issuecomment-2255610924

**Comment by pyrooka** [comment] 2024-07-29 12:17
Hi everyone! Thanks for all the feedback we are working on the fix. One thing that we can do is removing the `test` references from the `setup.py` file because - if I am correct - it's not used anymore. That should solve this issue. Give us a little time, we'll back soon!

**Comment by pyrooka** [comment] 2024-07-29 13:44
FYI, the latest `setuptools` release which caused this issue has been yanked, so all builds should run fine without any change. I still think we should remove the references to the deprecated code.
I leave this issue open for a while to make sure everything works fine, so feel free to give feedback here.

**Comment by bradhvr** [comment] 2024-07-29 16:37
@pyrooka Thanks for the quick responses on this!

**Comment by pyrooka** [comment] 2024-07-29 19:14
@bradhvr Of course! We are trying to support our users as much as possible. :)

**Comment by pyrooka** [comment] 2024-07-29 19:16
A new release - which removes the deprecated code from the project - was published not too long ago: https://pypi.org/project/ibm-cloud-sdk-core/3.20.4/

I'm closing this issue now, but feel free to re-open it if needed!

**Closed by pyrooka** 2024-07-29 19:16 UTC
